### ISSUE TITLE
What's the use-case of this?

### ISSUE THREAD

**Issue by anildigital** [pottava/fargate-shell#1]

**Comment by reini1989** [comment]
You place this Task in a public subnet, and some other stuff (taks, ec2 instances) in a private subnet. This Bastion task will allow you to ssh into the endpoints in the private subnet by ssh'ing into the bastion first, and from there ssh'ing to your final target.

Google bastion hosts for more information on this

**Comment by pottava** [comment]
@reini1989 Thanks for the comment. 
@anildigital Sorry, I had not noticed it for a long time.
